name: Manually triggered workflow
on: 
  workflow_dispatch:
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
import json
import os

def test_model_score():
    score = app.main()  # Assuming the main function returns the score
    assert isinstance(score, float)
    assert 0.0 <= score <= 1.0

    # Load the model scores
    with open('model_scores.json', 'r') as f:
        model_scores = json.load(f)

    # Get the latest model score
    latest_score = model_scores[-1]['score']

    # Compare the latest score with the current score
    assert score >= latest_score
